root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["up", "sillygame"]
  bin = "/mnt/c/Program Files/Docker/Docker/resources/bin/docker"
  cmd = "compose"
  delay = 0
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "web"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["web"]
  include_ext = ["go", "tpl", "tmpl", "html", "ts", "svelte"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
