version: 2.1
jobs:
  build-deploy:
    machine: true
    resource_class: moojigc/rocks_ci
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            echo 'Starting build...'
            sudo docker login $DOCKERHUB_HOST -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
            sudo docker build --pull --rm -f "Dockerfile" -t $DOCKERHUB_HOST/$CIRCLE_PROJECT_REPONAME:latest "."
      - run:
          name: Push Docker Image
          command: |
            echo 'Pushing to $DOCKERHUB_HOST...'
            sudo docker push $DOCKERHUB_HOST/$CIRCLE_PROJECT_REPONAME:latest
      - run:
          name: Run webhook
          command: |
            result=$(curl --location --request POST $WEBHOOK_URL \
              --header "X-Webhook-Password: $WEBHOOK_PASS" \
              --header "Content-Type: application/json" \
              --data-raw '{
              "container": "sillygame",
              "image": "sillygame",
              "tag": "latest",
              "stack": "portfolio"
              }')

            echo $result

            if [[ "$result" =~ 'exit status 1' ]]; then
              echo "Webhook failed to process."
              exit 1
            elif [[ "$result" =~ 'rules were not satisfied' ]]; then
              echo "Webhook setup improperly."
              exit 1
            fi
workflows:
  build:
    jobs:
      - build-deploy:
          context: elite
          filters:
            branches:
              only:
                - master
                - main